# Numpy
- Numpy란
    - 수치 데이터를 다루는 파이썬 패키지
    - Numpy는 다차원 배열을 효과적으로 처리할 수 있도록 도와주는 도구
    - 데이터 분석 및 ML/DL에서 많이 사용
    - 단일 자료형만 저장 가능하므로 속도나 메모리 효율성이 좋다 

##  Numpy 설치
- 설치 : !pip install numpy 
- [api](https://numpy.org/doc/stable/reference/index.html#reference)

In [1]:
import numpy as np

## 배열 초기화

### array 함수
* List 활용해서 선언

In [11]:
# 1차원 - List 활용한 초기화
my_list=[1, 2, 3]
my_arr=np.array(my_list) 

print("배열 출력:", my_arr)    
print("배열의 크기:", my_arr.size)
print("배열 차원의 크기:", my_arr.shape)     
print("배열의 차원 수:", my_arr.ndim)
print("배열의 원소타입:", my_arr.dtype)        # np.array(my_list, dtype='int64')
print("배열의 인덱스:", my_arr[2])

배열 출력: [1 2 3]
배열의 크기: 3
배열의 차원의 크기: (3,)
배열의 차원 수: 1
배열의 원소타입: int32
배열의 인덱스: 3


In [9]:
# 2차원 - List 활용한 초기화
arr=np.array([[5, 9, 10, 3, 1],
              [8, 3, 4, 2, 5]])

print("배열 출력:\n", arr)
print("배열의 크기:", arr.size)
print("배열 차원의 크기:", arr.shape)  
print("배열의 차원 수:", my_arr.ndim)
print("배열의 원소 타입:", arr.dtype)
print("배열의 인덱스:", arr[1][2])

배열 출력:
 [[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
배열의 크기: 10
배열의 차원의 크기: (2, 5)
배열의 차원 수: 2
배열의 원소 타입: int32
배열의 인덱스: 4


### arange 함수 
- arange(start, end, step)
- 파이썬의 내장함수 range(start, end, step) 동일

In [24]:
print("0~9 출력:", np.arange(0, 10, 1))        
print("0~9 출력:", np.arange(10))
print("10~50 step5:", np.arange(10, 50, 5))  

0~9 출력: [0 1 2 3 4 5 6 7 8 9]
0~9 출력: [0 1 2 3 4 5 6 7 8 9]
10~50 step5: [10 15 20 25 30 35 40 45]


### 다양한 형태의 함수 
- zeros() : 0으로 초기화
- ones()  : 1로 초기화
- full()  : 특정 숫자로 초기화
- eye()   : 대각선 1, 그외 0인 2차원 배열 초기화

In [27]:
# 0으로 초기화 
np.zeros((4, 4))               # defulat float

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.zeros((4, ), dtype=int)    # dtype=int >> int 32  
                              # dtype=np.int64

array([0, 0, 0, 0])

In [31]:
# 1로 초기화 
np.ones((3, 3), dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [33]:
# 특정 숫자(5)로 초기화
np.full((2, 3), fill_value=5)    

array([[5, 5, 5],
       [5, 5, 5]])

In [35]:
# 대각선 1, 그외 0인 2차원 배열
np.eye(3)           # 아이 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### random 함수 
- random() : 0 ~ 1 숫자 랜덤
- rand() : 0 ~ 1 균일한 값으로 랜덤 
- randint() : 0 ~ 9 정수 숫자 랜덤

In [11]:
# 5개의 랜덤
np.random.random(size=5)

array([0.58348747, 0.77000857, 0.28939164, 0.22877046, 0.3545336 ])

In [13]:
# 3행 2열 랜덤
np.random.random(size=(3, 2))

array([[0.20790414, 0.93949489],
       [0.37950577, 0.49044703],
       [0.93813658, 0.55008455]])

In [62]:
# 0~1 균일한 값으로 랜덤 5개
np.random.rand(5)                   

array([0.54781821, 0.98172794, 0.8641718 , 0.09721422, 0.58639148])

In [15]:
# 0~9 랜덤
np.random.randint(0, 10, size=10)    # np.random.randint(0, 10, size=(5, 5))       

array([6, 2, 4, 1, 7, 8, 5, 2, 7, 1])

In [63]:
# 배열에서 무작위 값들을 선택
arr=np.array([10, 20, 30, 40, 50])
np.random.choice(arr, size=3, replace=False)    # 배열에서 3개를 랜덤, 중복값 허용 안함

array([40, 20, 50])

## 배열 형태 바꾸기

### 차원 변환

In [23]:
a=np.arange(1, 9)      
print(a)

b=a.reshape(2, 4)     # 또는 np.reshape(a, (2,4)), 원본 데이터 영향 안 받음
print(b)

c=a.reshape(4, 2)
print(c)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [24]:
# 3차원 변환
d=a.reshape(2, 2, 2)
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 자동 재배열
* reshape (-1) 의미

In [5]:
x=np.arange(12)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [7]:
# 행의 위치에서 -1을 넣고 열의 수를 지정해주면 변환될 행은 알아서 자동으로 재배열
a=x.reshape(-1, 1)
print(a, "\n")

b=x.reshape(-1, 2)
print(b, "\n")

c=x.reshape(-1, 3)
print(c, "\n")

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]] 

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 



In [9]:
# 열의 위치에 -1을 넣고 행의 수를 지정해주면 열은 알아서 자동으로 재배열
i=x.reshape(1, -1)
print(i, "\n")

j=x.reshape(2, -1)
print(j, "\n")

k=x.reshape(3, -1)
print(k, "\n")

[[ 0  1  2  3  4  5  6  7  8  9 10 11]] 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



In [43]:
# reshape(-1) 경우는 1차원 배열 
arr=np.array([[1, 2, 3, 4, 5], 
              [6, 7, 8, 9, 10]])
arr=arr.reshape(-1)      # 1차원으로 변환, x.reshape(1 ,-1) 2차원 차이점 알아두기 
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# 전치행열 (행과 열을 바꿈)
a=np.array([[1, 2],
            [33, 44]])
print(a)
print()

print(a.T)

[[ 1  2]
 [33 44]]

[[ 1 33]
 [ 2 44]]


## 연산

### 사칙 연산

In [108]:
a=np.arange(1, 5)
print(a * 10)
print(np.multiply(a, 10)) 

print(a + 10)    # np.add(a, 10)
print(a - 10)    # np.subtract(a, 10)
print(a / 10)    # np.divide(a, 10)

[10 20 30 40]
[10 20 30 40]
[11 12 13 14]
[-9 -8 -7 -6]
[0.1 0.2 0.3 0.4]


In [42]:
b=a.reshape(2, 2)
print(b, "\n")

mul=b*100      
print(mul)

[[1 2]
 [3 4]] 

[[100 200]
 [300 400]]


In [45]:
c=np.arange(1, 5).reshape(2, 2)
print(c)

d=np.arange(11, 15).reshape(2, 2)
print(d, "\n")

hap=c+d
print(hap)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]] 

[[12 14]
 [16 18]]


### Broadcasting 연산
* 서로 다른 형태의 배열 연산

In [58]:
# 행 연산
x=np.arange(4).reshape(2, 2)
y=np.arange(2)
x+y

array([[0, 2],
       [2, 4]])

In [57]:
# 열 연산
i=np.arange(0, 16).reshape(4, 4)
j=np.arange(10, 14).reshape(4, 1)
i+j

array([[10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23],
       [25, 26, 27, 28]])

### masking 연산
* 특정 조건에 맞는 값을 추출, 이미지 처리에서 주로 활용, 반복문보다 속다 빠르고 간편

In [53]:
arr=np.arange(16).reshape(4, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [55]:
# 10보다 큰 수 출력 (반복)
for row in arr:
    for num in row:
        if num > 10:
            print(num)         

11
12
13
14
15


In [57]:
# Ex1) 조건에 따라 배열의 특정 값만 변경하고 싶을때  
# 조건에 해당하는 마스킹를 생성 - TRUE, FALSE
masking=arr > 10
print(masking, "\n")

# 필터링된 배열 정보 출력
f=arr[masking]        # arr[arr > 10] 또는 arr[arr % 2==0]
f

[[False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]] 



array([11, 12, 13, 14, 15])

In [59]:
# Ex2) TRUE을 100으로 바꾼다. (색상이 다른경우)
arr[arr > 5]=100    
arr

array([[  0,   1,   2,   3],
       [  4,   5, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [61]:
# Ex3) 빈 값 처리 
arr=np.array([1, 2, np.nan, 4, 5])
mask=~np.isnan(arr)
mask

print(arr[mask])     # arr[~np.isnan(arr)]

[1. 2. 4. 5.]


In [ ]:
# End Of ---------------------------------